// FOR NOW THESE ARE CONSTANTS BUT WITH A CATCH
// EACH OF THE OBJECT IN THE LIST REPRESENTS AN ISSUE STATE IN THE DATA-BASE
// SO IF YOU WISH TO RUN THIS PROJECT MAKE SURE TO CREATE THE STATES IN THE DB AND CHANGE THESE VALUES
// WHEN CREATING THE STATE IT NEEDS TO HAVE A "label" WHICH REPRESENTS THE BOARD-LIST WITH "isIssue" SET TO TRUE TO MAKE IT AN ISSUE STATE
// MAKE SURE BOTH LABEL AND _ID VALUES MATCH THE DB

export const boardLists = [
  {
    label: "AWAITING",
    stateId: "65f7c0ec47ca29e08d705586", // THIS IS THE AWAITING STATE _ID IN THE DB
  },
  { label: "IN_PROGRESS", stateId: "65f7c12547ca29e08d705587" }, // THIS IS THE IN_PROGRESS STATE _ID IN THE DB
  { label: "EVALUATION", stateId: "65f7c13e47ca29e08d705588" }, // THIS IS THE EVALUATION STATE _ID IN THE DB
  { label: "COMPLETED", stateId: "65f7c14b47ca29e08d705589" }, // THIS IS THE COMPLETED STATE _ID IN THE DB
];

// THESE ARE THE SAME AS THE ABOVE JUST MAP THE _ID WITH THE CORRESPONDING STATE
export const states = {
  AWAITING: { label: "TO-DO", value: "65f7c0ec47ca29e08d705586" }, // THIS IS THE AWAITING STATE _ID IN THE DB
  IN_PROGRESS: { label: "DOING", value: "65f7c12547ca29e08d705587" }, // THIS IS THE IN_PROGRESS STATE _ID IN THE DB
  EVALUATION: { label: "REVIEW", value: "65f7c13e47ca29e08d705588" }, // THIS IS THE EVALUATION STATE _ID IN THE DB
  COMPLETED: { label: "DONE", value: "65f7c14b47ca29e08d705589" }, // THIS IS THE COMPLETED STATE _ID IN THE DB
};
