// FOR NOW THESE ARE CONSTANTS BUT WITH A CATCH
// EACH OF THE OBJECT REPRESENTS A PROJECT STATE IN THE DATA-BASE
// SO IF YOU WISH TO RUN THIS PROJECT MAKE SURE TO CREATE THE STATES IN THE DB AND CHANGE THESE VALUES
// WHEN CREATING THE STATE IT NEEDS TO HAVE A "label" WHICH REPRESENTS THE PROJECT-STATE WITH "isProject" SET TO TRUE TO MAKE IT A PROJECT STATE
// MAKE SURE BOTH LABEL AND _ID VALUES MATCH THE DB

export const states = {
  WAITING: {
    _id: "65f7915d47ca29e08d705563", // THIS IS THE WAITING STATE _ID IN THE DB
    label: "WAITING",
    color: "rgb(205, 225, 255)",
  },
  STARTED: {
    _id: "65f7916847ca29e08d705566", // THIS IS THE STARTED STATE _ID IN THE DB
    label: "STARTED",
    color: "rgb(195, 255, 175)",
  },
  CLOSED: {
    _id: "65f7917e47ca29e08d705568", // THIS IS THE CLOSED STATE _ID IN THE DB
    label: "CLOSED",
    color: "rgb(255, 215, 210)",
  },
};
