// FOR NOW THESE ARE CONSTANTS BUT WITH A CATCH
// EACH OF THE ELEMENT REPRESENTS A LOG STATE IN THE DATA-BASE
// SO IF YOU WISH TO RUN THIS PROJECT MAKE SURE TO CREATE THE STATES IN THE DB AND CHANGE THESE VALUES
// WHEN CREATING THE STATE IT NEEDS TO HAVE A "label" WHICH REPRESENTS THE LOG-STATE WITH "isLog" SET TO TRUE TO MAKE IT A LOG STATE
// MAKE SURE BOTH LABEL AND _ID VALUES MATCH THE DB

export const states = {
  AWAITING: "65f7ab2b47ca29e08d70557a", // THIS IS THE AWAITING STATE _ID IN THE DB
  STARTED: "65f7ab3847ca29e08d70557b", // THIS IS THE STARTED STATE _ID IN THE DB
};
